[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"
authors = ["SmartCow AI Technologies"]
# The title and description fields are primarily for displaying extension info in UI
title = "LP-SDG"
description="A Synthetic Data Generator for ALPR Applications, particularly License Plate Generation."
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview.png"
#Icon is shown in Extensions window, it is recommended to be square of size 256x256.
icon = "data/logo.png"
# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"
# URL of the extension source repository.
repository = ""
# One of categories for UI.
category = "Other"
# Keywords for the extension
keywords = ["code", "sdg", "alpr", "license plate recognition", "license plate detection", "ocr", "computer vision"]


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.viewport.utility" = { optional = false } # Viewport utility tools
"omni.kit.viewport.window" = { optional = true } # Viewport-Next
"omni.kit.window.viewport" = { optional = true } # Viewport-Legacy
"omni.ui" = { optional = true } # Required for Viewport-Legacy adapter

# Main python module this extension provides, it will be publicly available as "import smartcow.ext.lp_sdg".
[[python.module]]
name = "smartcow.ext.lp_sdg"

[[test]]
args = [
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--no-window"
]